### ISSUE TITLE
crash in pop and inconssistent sizes on pipe ends

### ISSUE THREAD

**Issue by marriusco** [ict-project/libict-queue#1]
I have 2 processes.

### Issue 1, removing a pop-ed element ?

The provider is pushing 128000 length strings at a rate of 1 fps.
After insert i read the size and grows accordingly.

A consume process, now pops items from the same cache.
AT first it reads the size as it was last time set in the provide, then as pops, the
size() returns left items. Whatever on the pusher side the size()  keep growing.
Is this normal ?

```
D: cache has 8990 elements  << producer
D: cache has 8999 elements
...
cache has 1 elements  << consumer
```
If i shut down the consumer and start it again it starts again getting 
all the cached elements

### Issue 2
The cache has about 7000 elements, then i start the consumer, and 
start poping the program crashes at about 40's elements left, as

```
    void pop(Container & c){
        std::lock_guard<std::mutex> lock(readMutex);
        std::size_t s;
        queue.readSize(s);  <<<< ===== here
        c.resize(s/sizeof(c[0]));
        queue.readContent((char*)&c[0]);
    }

1  __GI_raise                                                            raise.c              50   0x7f8352e9000b 
2  __GI_abort                                                            abort.c              79   0x7f8352e6f859 
3  ??                                                                                              0x7f8353247911 
4  ??                                                                                              0x7f835325338c 
5  std::terminate()                                                                                0x7f83532533f7 
6  __cxa_throw                                                                                     0x7f83532536a9 
7  ict::queue::basic::readSize(unsigned long&) [clone .cold]                                       0x55961ee3018a 


```

**Comment by ict-project** [comment]
Thank you for your feedback.

The problem here is that this queue was designed with assumption that in given point of time there is only one instance of queue bonded to given file cache. Metadata from files (including size of the queue) is loaded at construction of the queue (and then maintained inside). If other instance modify queue then the first one is not aware of it (it has to be destructed and constructed again in order to load current metadata).

However the feature of multiple instances accessing simultaneously to one file cache is quite interesting. I need to think it over. It needs some file locking mechanism and metadata actualization.

**Comment by ict-project** [comment]
As of version v2.0, concurrent access to the directory with the queue data is possible by many independent processes.
Try now please and let me know if it works for you.
